// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApsQqQH4FE2_ToBmAs6iUQwhL-rk89xYk',
    appId: '1:1025042153577:web:964ab6c1312a70e005e2f8',
    messagingSenderId: '1025042153577',
    projectId: 'newuser-18df0',
    authDomain: 'newuser-18df0.firebaseapp.com',
    storageBucket: 'newuser-18df0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuC5hmv0tMk52bisikHD94foY7zBM_SaY',
    appId: '1:1025042153577:android:478369a3de73553605e2f8',
    messagingSenderId: '1025042153577',
    projectId: 'newuser-18df0',
    storageBucket: 'newuser-18df0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9KuK4eYCUEX7BWE-MHRUGeJ7ebqJOtM',
    appId: '1:1025042153577:ios:c6e9f7ca20617c9105e2f8',
    messagingSenderId: '1025042153577',
    projectId: 'newuser-18df0',
    storageBucket: 'newuser-18df0.firebasestorage.app',
    iosBundleId: 'com.example.newuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH9KuK4eYCUEX7BWE-MHRUGeJ7ebqJOtM',
    appId: '1:1025042153577:ios:c6e9f7ca20617c9105e2f8',
    messagingSenderId: '1025042153577',
    projectId: 'newuser-18df0',
    storageBucket: 'newuser-18df0.firebasestorage.app',
    iosBundleId: 'com.example.newuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApsQqQH4FE2_ToBmAs6iUQwhL-rk89xYk',
    appId: '1:1025042153577:web:ad8a09ec0d356e3e05e2f8',
    messagingSenderId: '1025042153577',
    projectId: 'newuser-18df0',
    authDomain: 'newuser-18df0.firebaseapp.com',
    storageBucket: 'newuser-18df0.firebasestorage.app',
  );
}
